=== baradhili/resume-schema/job-schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://raw.githubusercontent.com/jgilman1337/resume-schema/refs/heads/master/job-schema.json",
	"title": "Job Description Schema",
	"description": "This schema is for defining a job description",
	"version": "2.0.0",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"title": {
			"type": "string",
			"description": "The name of the job, e.g. 'Web Developer'."
		},
		"company": {
			"type": "string",
			"description": "The company offering the role, e.g. 'Microsoft'."
		},
		"type": {
			"description": "The type of job this is, e.g. Full-time, part-time, contract, etc.",
			"$ref": "types.json#/definitions/jobType"
		},
		"date": {
			"description": "The date the job was posted in ISO8601 format.",
			"$ref": "types.json#/definitions/iso8601"
		},
		"description": {
			"type": "string",
			"description": "A short description about the job."
		},
		"location": {
			"description": "Where the job is located. For fully remote jobs, simply fill in the country code of the position and leave the other fields as `null`.",
			"$ref": "types.json#/definitions/location"
		},
		"remote": {
			"type": "string",
			"description": "The level of remote work available, where 'Full' is fully online and 'None' is strictly in-person.",
			"enum": [
				"Full",
				"Hybrid",
				"None"
			]
		},
		"salary": {
			"type": "string",
			"description": "The expected salary or range of salaries plus the base time unit, e.g. $100,000/yearly, $5,000 - $6,000/monthly, $25/hourly."
		},
		"experience": {
			"description": "The experience level required for the job, e.g. 'Senior', 'Junior', 'Mid-level'.",
			"$ref": "types.json#/definitions/experienceLevel"
		},
		"responsibilities": {
			"type": "array",
			"description": "What the job entails.",
			"additionalItems": false,
			"items": {
				"type": "string",
				"description": "e.g. Build out a new API for our customer base."
			}
		},
		"qualifications": {
			"type": "array",
			"description": "A list of the qualifications that are required for this position.",
			"additionalItems": false,
			"items": {
				"type": "string",
				"description": "The required qualification, e.g. 'undergraduate degree'."
			}
		},
		"optionalQualifications": {
			"type": "array",
			"description": "A list of the qualifications that are optional for this position.",
			"additionalItems": false,
			"items": {
				"type": "string",
				"description": "The optional qualification, e.g. 'undergraduate degree'."
			}
		},
		"keywords": {
			"description": "A list of keywords pertaining to the listing; sourced from the qualifications (required and optional), job description, and responsibilities.",
			"$ref": "types.json#/definitions/keywords"
		},
		"skills": {
			"type": "array",
			"description": "A list of the skills utilized while doing work for the job.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "The name of the skill, e.g. 'Web Development'."
					},
					"level": {
						"description": "The mastery level of the skill.",
						"$ref": "types.json#/definitions/masteryLevel"
					},
					"keywords": {
						"description": "A list of keywords pertaining to this specific skill.",
						"$ref": "types.json#/definitions/keywords"
					}
				}
			}
		},
		"meta": {
			"$ref": "types.json#/definitions/meta"
		}
	},
	"required": [
		"meta"
	]
}

=== baradhili/resume-schema/sample.job.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Web Developer",
	"company": "Microsoft",
	"type": "Full-time",
	"date": "2024-07",
	"description": "We are looking for a skilled Web Developer to join our team. The role involves building and maintaining web applications.",
	"location": {
		"address": "1234 Glücklichkeit Straße\nHinterhaus 5. Etage li.",
		"postalCode": "10115",
		"city": "Berlin",
		"countryCode": "DE",
		"region": "Berlin"
	},
	"remote": "Hybrid",
	"salary": "100000",
	"experience": "Mid-level",
	"responsibilities": [
		"Develop and maintain web applications",
		"Collaborate with cross-functional teams",
		"Ensure the technical feasibility of UI/UX designs",
		"Optimize applications for maximum speed and scalability"
	],
	"qualifications": [
		"Bachelor's degree in Computer Science or related field",
		"3+ years of experience in web development",
		"Strong understanding of JavaScript, HTML, and CSS"
	],
	"skills": [
		{
			"name": "Web Development",
			"level": "Master",
			"keywords": [
				"HTML",
				"CSS",
				"JavaScript",
				"React",
				"Node.js"
			]
		},
		{
			"name": "Database Management",
			"level": "Intermediate",
			"keywords": [
				"SQL",
				"NoSQL",
				"MongoDB"
			]
		}
	],
	"meta": {
		"canonical": "http://example.com/jobs/web-developer",
		"version": "v1.0.0",
		"lastModified": "2024-07-10T15:00:00"
	}
}
