=== baradhili/resume-schema/schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://raw.githubusercontent.com/jgilman1337/resume-schema/refs/heads/master/schema.json",
	"title": "Resume Schema",
	"version": "2.0.0",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"basics": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"name": {
					"type": "string",
					"description": "The name of the resume's subject."
				},
				"label": {
					"type": "string",
					"description": "The subject's professional title, e.g. Web Developer."
				},
				"image": {
					"type": "string",
					"description": "URL (as per RFC 3986) to an image in JPEG or PNG format.",
					"format": "uri"
				},
				"email": {
					"type": "string",
					"description": "The subject's email address, e.g. 'thomas@gmail.com'.",
					"format": "email"
				},
				"phone": {
					"type": "string",
					"description": "The contact phone number of the subject. Phone numbers are stored as strings so use any format preferred, e.g.'712-117-2923'."
				},
				"summary": {
					"type": "string",
					"description": "A short 2-3 sentence biography about the subject."
				},
				"location": {
					"description": "Where the subject is from. Can be a general region or their exact home address.",
					"$ref": "types.json#/definitions/location"
				},
				"links": {
					"type": "array",
					"description": "A list of web links relevant to the subject, e.g. personal website, social media, portfolios, etc.",
					"additionalItems": false,
					"items": {
						"type": "object",
						"additionalProperties": false,
						"properties": {
							"url": {
								"type": "string",
								"description": "e.g. https://github.com/johndoe",
								"format": "uri"
							},
							"label": {
								"type": "string",
								"description": "The label for the hyperlink, e.g. '@johndoe'."
							}
						}
					}
				}
			}
		},
		"work": {
			"type": "array",
			"description": "A list of past and present professional work done, sorted chronologically from latest to earliest.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"employer": {
						"type": "string",
						"description": "The name of the company, e.g. 'Facebook'."
					},
					"location": {
						"type": "string",
						"description": "The location the job is/was, e.g. 'Menlo Park, CA'. If the job is/was remote, specify 'Remote'."
					},
					"description": {
						"type": "string",
						"description": "A short, 1 sentence maximum description of the company, e.g. 'Social Media Company'."
					},
					"position": {
						"type": "string",
						"description": "The title of the role, e.g. 'Software Engineer'."
					},
					"url": {
						"type": "string",
						"description": "The relevant URL of the company's homepage, e.g. 'http://facebook.example.com'.",
						"format": "uri"
					},
					"startDate": {
						"description": "The date on which this position was started.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"endDate": {
						"description": "The date on which this position was stopped. If current and ongoing, specify a blank string as the value for this key.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"summary": {
						"type": "string",
						"description": "An overview of the responsibilities at the company. No more than 3-5 sentences."
					},
					"highlights": {
						"type": "array",
						"description": "A list of the key highlights of the volunteer role. For best results, use the XYZ formula with quantifiable attributes.",
						"additionalItems": false,
						"items": {
							"type": "string",
							"description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising."
						}
					},
					"keywords": {
						"description": "A list of keywords pertaining to this job position.",
						"$ref": "types.json#/definitions/keywords"
					}
				}
			}
		},
		"volunteer": {
			"type": "array",
			"description": "A list of past and present volunteer work done, sorted chronologically from latest to earliest.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"organization": {
						"type": "string",
						"description": "The name of the volunteer organization, e.g. 'American Red Cross'."
					},
					"position": {
						"type": "string",
						"description": "The title of the volunteer role, e.g. 'Customer Service Representative'."
					},
					"url": {
						"type": "string",
						"description": "The relevant URL of the volunteer organization's homepage, e.g. 'http://redcross.example.com'.",
						"format": "uri"
					},
					"startDate": {
						"description": "The date on which this volunteer position was started.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"endDate": {
						"description": "The date on which this volunteer position was stopped. If current and ongoing, specify a blank string as the value for this key.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"summary": {
						"type": "string",
						"description": "An overview of the responsibilities at the volunteer organization. No more than 3-5 sentences."
					},
					"highlights": {
						"type": "array",
						"description": "A list of the key highlights of the volunteer role. For best results, use the XYZ formula with quantifiable attributes.",
						"additionalItems": false,
						"items": {
							"type": "string",
							"description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising."
						}
					},
					"keywords": {
						"description": "A list of keywords pertaining to this volunteer position.",
						"$ref": "types.json#/definitions/keywords"
					}
				}
			}
		},
		"education": {
			"type": "array",
			"description": "A list of past and present institutions attended, sorted chronologically from latest to earliest.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"institution": {
						"type": "string",
						"description": "The name of the institution being attended, e.g. 'Massachusetts Institute of Technology'."
					},
					"subInstitution": {
						"type": "string",
						"description": "A specific college/school/department within the institution, e.g. 'College of Arts and Humanities'."
					},
					"url": {
						"type": "string",
						"description": "The relevant URL of the institution's homepage, e.g. 'http://example.com.edu'.",
						"format": "uri"
					},
					"subInstitutionUrl": {
						"type": "string",
						"description": "The relevant URL of the sub-institution's homepage, if different, e.g. 'https://example.com.edu/arts-humanities'.",
						"format": "uri"
					},
					"location": {
						"type": "string",
						"description": "The location of the institution, e.g. 'Boston, MA'."
					},
					"area": {
						"type": "string",
						"description": "The broad area of study, e.g. 'Engineering', 'Humanities'."
					},
					"programs": {
						"type": "array",
						"description": "One or more programs/majors pursued at this institution. Each item includes a degree designation and a name.",
						"minItems": 1,
						"items": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"type": {
									"type": "string",
									"description": "The broad education type for this program.",
									"enum": [
										"Degree",
										"Certificate",
										"Diploma",
										"Non-Degree",
										"Professional",
										"Other"
									]
								},
								"designation": {
									"type": "string",
									"description": "The degree designation or abbreviation of it, e.g. 'Bachelor of Science/B.S.', 'Master of Arts/M.A.', 'Associate of Applied Science/A.A.S'."
								},
								"name": {
									"type": "string",
									"description": "Specific major/minor name, e.g. 'Computer Science', 'Economics'."
								},
								"concentration": {
									"type": "string",
									"description": "Concentration or track within the major/minor, if applicable, e.g., 'Artificial Intelligence'."
								},
								"minor": {
									"type": "boolean",
									"description": "Indicates if this program is a minor rather than a major."
								},
								"gpa": {
									"type": "string",
									"description": "The cumulative grade point average (GPA) for this program, e.g. '3.67/4.0'."
								},
								"honors": {
									"type": "string",
									"description": "Honors or distinctions associated with this program, e.g., 'Summa Cum Laude'."
								}
							},
							"required": [
								"name",
								"type"
							]
						}
					},
					"startDate": {
						"description": "The date on which the education at this institution was started.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"endDate": {
						"description": "The date on which the education at this institution was stopped. If current and ongoing, specify a blank string as the value for this key.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"gpa": {
						"type": "string",
						"description": "The cumulative grade point average (GPA), e.g. '3.67/4.0'."
					},
					"courses": {
						"type": "array",
						"description": "A list of relevant courses/subjects.",
						"additionalItems": false,
						"items": {
							"type": "string",
							"description": "The course id/code and name, e.g. 'H1302 - Introduction to American History'."
						}
					},
					"awards": {
						"type": "array",
						"description": "Awards or honors earned for this program, e.g. 'Dean's List', 'Graduated with Honors'.",
						"items": {
							"type": "string"
						}
					},
					"extracurriculars": {
						"type": "array",
						"description": "A list of relevant extracurricular activities participated in while a student at the institution, e.g. 'Bird Watching Club', 'Association of Computing Machinery'.",
						"items": {
							"type": "string"
						}
					},
					"keywords": {
						"description": "A list of keywords pertaining to this education.",
						"$ref": "types.json#/definitions/keywords"
					},
					"notes": {
						"type": "string",
						"description": "Optional free-text notes, e.g. 'part-time study', 'transfer credits'."
					}
				}
			}
		},
		"awards": {
			"type": "array",
			"description": "A list of awards and distinctions received, sorted chronologically from latest to earliest.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"title": {
						"type": "string",
						"description": "The title of the award, e.g. 'Nobel Peace Prize'."
					},
					"date": {
						"$ref": "types.json#/definitions/iso8601"
					},
					"awarder": {
						"type": "string",
						"description": "The organization or entity that conferred the award, e.g. 'Time Magazine'."
					},
					"summary": {
						"type": "string",
						"description": "A short 1-2 sentence description of the award, e.g. 'Received for my work with Quantum Physics'."
					},
					"keywords": {
						"description": "A list of keywords pertaining to this award.",
						"$ref": "types.json#/definitions/keywords"
					}
				}
			}
		},
		"certificates": {
			"type": "array",
			"description": "A list of certificates awarded, sorted chronologically from latest to earliest.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "The title of the certificate, e.g. 'Certified Kubernetes Administrator'."
					},
					"date": {
						"description": "The date the certificate was issued.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"issuer": {
						"type": "string",
						"description": "The organization or entity that awarded the certificate, e.g. 'CNCF'."
					},
					"url": {
						"type": "string",
						"description": "The relevant URL of the awarding organization's homepage, e.g. 'http://example.com'.",
						"format": "uri"
					},
					"id": {
						"type": "string",
						"description": "The ID number of the certificate for verification purposes, if applicable."
					},
					"keywords": {
						"description": "A list of keywords pertaining to this certificate.",
						"$ref": "types.json#/definitions/keywords"
					}
				}
			}
		},
		"publications": {
			"type": "array",
			"description": "A list of past and present publications made, sorted chronologically from latest to earliest.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "The name of the publication, e.g. 'The World Wide Web'."
					},
					"publisher": {
						"type": "string",
						"description": "The name of the organization or entity that published the publication, e.g. 'IEEE, Computer Magazine'."
					},
					"releaseDate": {
						"description": "The date of the publication.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"url": {
						"type": "string",
						"description": "e.g. http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html",
						"format": "uri"
					},
					"summary": {
						"type": "string",
						"description": "A short summary of publication, e.g. 'Discussion of the World Wide Web, HTTP, HTML'."
					},
					"keywords": {
						"description": "A list of keywords pertaining to this publication.",
						"$ref": "types.json#/definitions/keywords"
					}
				}
			}
		},
		"skills": {
			"type": "array",
			"description": "A list of professional skills, including their mastery level.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "The name of the skill, e.g. 'Web Development'."
					},
					"level": {
						"description": "The experience level of the skill, e.g. 'Senior', 'Junior', 'Mid-level'.",
						"$ref": "types.json#/definitions/experienceLevel"
					},
					"keywords": {
						"description": "A list of keywords pertaining to this skill.",
						"$ref": "types.json#/definitions/keywords"
					}
				}
			}
		},
		"languages": {
			"type": "array",
			"description": "A list of languages spoken and/or written.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"language": {
						"type": "string",
						"description": "e.g. English, Spanish"
					},
					"fluency": {
						"type": "string",
						"description": "The proficiency in utilizing this language according to the CEFR.",
						"enum": [
							"Beginner",
							"Intermediate",
							"Advanced",
							"Proficient",
							"Native"
						]
					}
				}
			}
		},
		"interests": {
			"type": "array",
			"description": "A list of personal interests that lie outside one's professional work (i.e. hobbies).",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "The name of the interest, e.g. 'Philosophy'."
					},
					"keywords": {
						"description": "A list of keywords pertaining to this interest.",
						"$ref": "types.json#/definitions/keywords"
					}
				}
			}
		},
		"references": {
			"type": "array",
			"description": "A list of references/letters of recommendation received.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "The person who wrote the reference, e.g. 'Timothy Cook'."
					},
					"reference": {
						"type": "string",
						"description": "e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing."
					}
				}
			}
		},
		"projects": {
			"type": "array",
			"description": "A list of past and present professional or personal projects done, sorted chronologically from latest to earliest.",
			"additionalItems": false,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "The name of the project, e.g. 'The World Wide Web'."
					},
					"description": {
						"type": "string",
						"description": "A short summary of project in 1-3 sentences. e.g. 'Collated works of 2017'."
					},
					"highlights": {
						"type": "array",
						"description": "A list of the key highlights of the project. For best results, use the XYZ formula with quantifiable attributes.",
						"additionalItems": false,
						"items": {
							"type": "string",
							"description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising."
						}
					},
					"keywords": {
						"description": "A list of keywords pertaining to this project.",
						"$ref": "types.json#/definitions/keywords"
					},
					"startDate": {
						"description": "The date on which work on this project was started.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"endDate": {
						"description": "The date on which work on this project was stopped. If current and ongoing, specify a blank string as the value for this key.",
						"$ref": "types.json#/definitions/iso8601"
					},
					"url": {
						"type": "string",
						"format": "uri",
						"description": "e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html"
					},
					"roles": {
						"type": "array",
						"description": "A list of the roles taken on during the development of the project.",
						"additionalItems": false,
						"items": {
							"type": "string",
							"description": "e.g. Team Lead, Speaker, Writer"
						}
					},
					"entity": {
						"type": "string",
						"description": "The relevant company/entity affiliations, if any, e.g. 'greenpeace', 'corporationXYZ'."
					},
					"type": {
						"type": "string",
						"description": " e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'"
					}
				}
			}
		},
		"meta": {
			"$ref": "types.json#/definitions/meta"
		}
	},
	"required": [
		"meta"
	]
}

=== baradhili/resume-schema/sample.resume.json
{
	"basics": {
		"name": "Richard Hendriks",
		"label": "Programmer",
		"image": "",
		"email": "richard.hendriks@mail.com",
		"phone": "(912) 555-4321",
		"summary": "Richard hails from Tulsa. He has earned degrees from the University of Oklahoma and Stanford. (Go Sooners and Cardinal!) Before starting Pied Piper, he worked for Hooli as a part time software developer. While his work focuses on applied information theory, mostly optimizing lossless compression schema of both the length-limited and adaptive variants, his non-work interests range widely, everything from quantum computing to chaos theory. He could tell you about it, but THAT would NOT be a “length-limited” conversation!",
		"location": {
			"address": "2712 Broadway St",
			"postalCode": "CA 94115",
			"city": "San Francisco",
			"countryCode": "US",
			"region": "California"
		},
		"links": [
			{
				"url": "https://www.twitter.com/neutralthoughts",
				"label": "@neutralthoughts"
			},
			{
				"url": "https://soundcloud.example.com/dandymusicnl",
				"label": "@dandymusicnl"
			}
		]
	},
	"work": [
		{
			"employer": "Pied Piper",
			"location": "Palo Alto, CA",
			"description": "Awesome compression company",
			"position": "CEO/President",
			"url": "http://piedpiper.example.com",
			"startDate": "2013-12-01",
			"endDate": "2014-12-01",
			"summary": "Pied Piper is a multi-platform technology based on a proprietary universal compression algorithm that has consistently fielded high Weisman Scores™ that are not merely competitive, but approach the theoretical limit of lossless compression.",
			"highlights": [
				"Build an algorithm for artist to detect if their music was violating copy right infringement laws",
				"Successfully won Techcrunch Disrupt",
				"Optimized an algorithm that holds the current world record for Weisman Scores"
			]
		}
	],
	"volunteer": [
		{
			"organization": "CoderDojo",
			"position": "Teacher",
			"url": "http://coderdojo.example.com/",
			"startDate": "2012-01-01",
			"endDate": "2013-01-01",
			"summary": "Global movement of free coding clubs for young people.",
			"highlights": [
				"Awarded 'Teacher of the Month'"
			]
		}
	],
	"education": [
		{
			"institution": "University of Oklahoma",
			"url": "https://www.ou.edu/",
			"area": "Information Technology",
			"startDate": "2011-06-01",
			"endDate": "2014-01-01",
			"programs": [
				{
					"type": "Degree",
					"designation": "Bachelor of Science/B.S.",
					"name": "Information Technology",
					"gpa": "4.0"
				}
			],
			"courses": [
				"DB1101 - Basic SQL",
				"CS2011 - Java Introduction"
			]
		}
	],
	"awards": [
		{
			"title": "Digital Compression Pioneer Award",
			"date": "2014-11-01",
			"awarder": "Techcrunch",
			"summary": "There is no spoon."
		}
	],
	"publications": [
		{
			"name": "Video compression for 3d media",
			"publisher": "Hooli",
			"releaseDate": "2014-10-01",
			"url": "http://en.wikipedia.org/wiki/Silicon_Valley_(TV_series)",
			"summary": "Innovative middle-out compression algorithm that changes the way we store data."
		}
	],
	"skills": [
		{
			"name": "Web Development",
			"level": "Advanced",
			"keywords": [
				"HTML",
				"CSS",
				"Javascript"
			]
		},
		{
			"name": "Compression",
			"level": "Intermediate",
			"keywords": [
				"Mpeg",
				"MP4",
				"GIF"
			]
		}
	],
	"languages": [
		{
			"language": "English",
			"fluency": "Native"
		}
	],
	"interests": [
		{
			"name": "Wildlife",
			"keywords": [
				"Ferrets",
				"Unicorns"
			]
		}
	],
	"references": [
		{
			"name": "Erlich Bachman",
			"reference": "It is my pleasure to recommend Richard, his performance working as a consultant for Main St. Company proved that he will be a valuable addition to any company."
		}
	],
	"projects": [
		{
			"name": "Miss Direction",
			"description": "A mapping engine that misguides you",
			"highlights": [
				"Won award at AIHacks 2016",
				"Built by all women team of newbie programmers",
				"Using modern technologies such as GoogleMaps, Chrome Extension and Javascript"
			],
			"keywords": [
				"GoogleMaps",
				"Chrome Extension",
				"Javascript"
			],
			"startDate": "2016-08-24",
			"endDate": "2016-08-24",
			"url": "http://missdirection.example.com",
			"roles": [
				"Team lead",
				"Designer"
			],
			"entity": "Smoogle",
			"type": "application"
		}
	],
	"meta": {
		"canonical": "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/sample.resume.json",
		"version": "1.0.0",
		"lastModified": "2026-02-27T00:00:00.000Z"
	}
}
